on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run cover

      - name: Coveralls
        if: success()
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        id: build
        run: |
          npm run build
          PKG_FILE=$(npm pack | tail -n 1)
          echo "filename=$PKG_FILE" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.build.outputs.filename }}
          path: ${{ steps.build.outputs.filename }}

      - name: Check tag version
        if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
        run: |
          TAG_VERSION="${GITHUB_REF_NAME#v}"
          PACKAGE_VERSION="$(node -p "require('./package.json').version")"

          echo "Tag version: ${TAG_VERSION}"
          echo "Package version: ${PACKAGE_VERSION}"

          if [ "$TAG_VERSION" != "$PACKAGE_VERSION" ]; then
            echo "Tag version does not match package.json version"
            exit 1
          fi

      - name: Publish
        if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
        run: echo should run npm publish ${{ steps.build.outputs.filename }}
